version: '3.8'

services:
  web:
    build:
      context: ./RealDeal.Bet
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Redirige le port 8080 de l'hôte vers le conteneur
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RealDealDb;User=sa;Password=YourStrong!Password
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433" # Redirige le port 1433 pour SQL Server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Password
      - MSSQL_PID=Express
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
